import userModel from "../models/userModel.js"
import validator from "validator";
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken'

const createToken =(id)=>{
    return jwt.sign({id},process.env.JWT_SECRET);
}

const loginUser= async(req,res)=>{
    try {
        const {email,password}=req.body;
        const user = await userModel.findOne({email});
        if(!user){
            return res.json({success: false,message:"user doest not exists"});
        }
        const isMatch = await bcrypt.compare(password,user.password);
        if(isMatch){
            const token = createToken(user._id);
            res.json({success:true, token})
        }
        else{
            res.json({success:false, message:'Invalid credentials'})
        }
    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message})
    }
}
//route for user registration
const registerUser = async(req,res)=>{
    try {
        const {name,email,password}=req.body;
        //check if same email exist or not
        const exists= await userModel.findOne({email});
        if(exists){
            return res.json({success: false,message:"user already exists"});
        }
    //validating email format and strong pass
    if(!validator.isEmail(email)){
        return res.json({success: false,message:"Please enter a valid email"});
    }
    if(password.length<8){
        return res.json({success: false, message:"password length should be greater than 8"});
    }
    //hassing user pass
    const salt= await bcrypt.genSalt(10)
    const hashedPassword= await bcrypt.hash(password,salt)
    const newUser= new userModel({
        name,
        email,
        password: hashedPassword
    })
    const user= await newUser.save() //whenever new user generate a new _id will also generate
    const token = createToken(user._id)//id is autogenerated in mongodb database
    res.json({success:true,token})

    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message})
    }
}
//route for admin login
const adminLogin = async(req,res)=>{

}
export {loginUser,registerUser,adminLogin}